version: '2'
services:
 mysql:
    image: mysql
    container_name: mysql
    restart: "on-failure"
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=alfresco
      - MYSQL_USER=alfresco
      - MYSQL_PASSWORD=secret
      - GOSU_VERSION=1.7
      - MYSQL_MAJOR=5.7
      - MYSQL_VERSION=5.7.21-1debian9
    volumes:
      - '~/docker/volumes/ventanilla/mysql:/var/lib/mysql'
    networks:
     net_docker:
      ipv4_address: 10.5.5.7
      
 alfresco:
    build: .
    image: alfresco:3.4.d
    container_name: alfresco
    restart: "on-failure"
    ports:
      - '8180:8080'
    environment:
      - CONTENT_STORE=/content
      - DB_KIND=mysql
      - DB_HOST=mysql
      - DB_NAME=alfresco
      - DB_USERNAME=alfresco
      - DB_PASSWORD=secret
      - ALFRESCO_ADMIN_PASSWORD=admin
    volumes:
      - '~/docker/volumes/ventanilla/alfresco/logs:/alfresco/tomcat/logs'
      - '~/docker/volumes/ventanilla/alfresco/alfresco_content_store:/content'
    depends_on:
      - mysql
    links:
      - mysql
    networks:
     net_docker:
      ipv4_address: 10.5.5.8
networks:
 net_docker:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 10.5.5.0/24
      gateway: 10.5.5.1
